//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.App.Badges.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.App.Badges.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All badges.
        /// </summary>
        public static string AllBadges {
            get {
                return ResourceManager.GetString("AllBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded by.
        /// </summary>
        public static string AwardedBy {
            get {
                return ResourceManager.GetString("AwardedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} awarded a badge to.
        /// </summary>
        public static string AwardedTo {
            get {
                return ResourceManager.GetString("AwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string BadgeCriteria {
            get {
                return ResourceManager.GetString("BadgeCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BadgeDescription {
            get {
                return ResourceManager.GetString("BadgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BadgeName {
            get {
                return ResourceManager.GetString("BadgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new badge.
        /// </summary>
        public static string CreateBadgeDescription {
            get {
                return ResourceManager.GetString("CreateBadgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create badge.
        /// </summary>
        public static string CreateBadgeName {
            get {
                return ResourceManager.GetString("CreateBadgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your team owner adds badges, they will appear here..
        /// </summary>
        public static string EmptyAllBadgesDescription {
            get {
                return ResourceManager.GetString("EmptyAllBadgesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No badges to show.
        /// </summary>
        public static string EmptyAllBadgesTitle {
            get {
                return ResourceManager.GetString("EmptyAllBadgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no badges yet..
        /// </summary>
        public static string EmptyYourBadgesDescription {
            get {
                return ResourceManager.GetString("EmptyYourBadgesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No badges to show.
        /// </summary>
        public static string EmptyYourBadgesTitle {
            get {
                return ResourceManager.GetString("EmptyYourBadgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ExceptionResponse {
            get {
                return ResourceManager.GetString("ExceptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into Badgr with the same email address you use for Microsoft Teams..
        /// </summary>
        public static string InvalidAccountText {
            get {
                return ResourceManager.GetString("InvalidAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this app. Contact your IT admin..
        /// </summary>
        public static string InvalidTenant {
            get {
                return ResourceManager.GetString("InvalidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0} Way to go! - {1}.
        /// </summary>
        public static string MentionText {
            get {
                return ResourceManager.GetString("MentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find any matches..
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find team. Please try opening again from team where app was installed..
        /// </summary>
        public static string NoTeamFound {
            get {
                return ResourceManager.GetString("NoTeamFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text can&apos;t exceed 100 characters. Please update..
        /// </summary>
        public static string NoteCharacterLimitExceeded {
            get {
                return ResourceManager.GetString("NoteCharacterLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples: Leading across teams, Most new partnerships in Q4.
        /// </summary>
        public static string NoteForReceipientsPlaceholder {
            get {
                return ResourceManager.GetString("NoteForReceipientsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string NoteForRecipients {
            get {
                return ResourceManager.GetString("NoteForRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string OnDate {
            get {
                return ResourceManager.GetString("OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preview.
        /// </summary>
        public static string PreviewBadgeTitle {
            get {
                return ResourceManager.GetString("PreviewBadgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one or more names or emails.
        /// </summary>
        public static string SearchTeamMembers {
            get {
                return ResourceManager.GetString("SearchTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one recipient.
        /// </summary>
        public static string SelectAtleastOneMember {
            get {
                return ResourceManager.GetString("SelectAtleastOneMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a badge to award.
        /// </summary>
        public static string SelectBadge {
            get {
                return ResourceManager.GetString("SelectBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please sign in again to proceed..
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view or award badges, you’ll need to sign in..
        /// </summary>
        public static string SignInCardText {
            get {
                return ResourceManager.GetString("SignInCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In required.
        /// </summary>
        public static string SignInRequired {
            get {
                return ResourceManager.GetString("SignInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and award badges.
        /// </summary>
        public static string TaskModuleTitle {
            get {
                return ResourceManager.GetString("TaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient(s).
        /// </summary>
        public static string ToBeAwardedTo {
            get {
                return ResourceManager.GetString("ToBeAwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access!.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and award badges right in Teams! Thousands of orgs use Open Badges to recognize learning and achievement. These badges have verifiable data and can be shared across the web..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Open Badges.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your badges.
        /// </summary>
        public static string YourBadges {
            get {
                return ResourceManager.GetString("YourBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preview.
        /// </summary>
        public static string YourPreview {
            get {
                return ResourceManager.GetString("YourPreview", resourceCulture);
            }
        }
    }
}
